import React from "react";
import "./../scss/TermsAndConditions.scss";
function CookiesPolicy(props) {
  return (
    <div className="__TermsAndConditions">
      <div className>
        <div className="content-area marginTop">
          <div className="about-content">
            <h1 style={{ textAlign: "center" }}>Cookies Policy</h1>
            <div>
              <p>
                <strong>What are Cookies?</strong>
              </p>
              <p>
                Cookies are small text files that are stored by the browser (for
                example, Internet Explorer) on your computer or device. You can
                think of cookies as providing a memory for the website, so that
                it can recognise you when you come back and respond
                appropriately.{" "}
              </p>
              <p>
                <strong>How we use Cookies?</strong>
              </p>
              <p>
                We use cookies to understand your use of our Services; improve
                your user experience and enable personalised features and
                content; optimise our advertisements and marketing; and to
                enable third-party advertising companies to assist us in serving
                ads specific to your interests.{" "}
              </p>
              <p>
                <strong>Are cookies harmful to my computer?</strong>
              </p>
              <p>
                No they are not dangerous for your computer and they do not in
                any way infringe your privacy rights. Cookies are, in fact,
                nothing more than very small text files that are placed on your
                computer/browser when you visit our website.
              </p>
              <p>
                <strong>Third-party Cookies</strong>
              </p>
              <p>
                When visiting our website, you may receive cookies both from the
                site being visited and from websites managed by other
                organizations ("third parties"). A notable example is the
                presence of "social plugins" for Facebook, Twitter, Google+,
                LinkedIn, etc. Such sections of the page visited are directly
                generated by these websites and integrated into the page of the
                host website. The management of the information collected by
                "third parties" is governed by their relevant policies The
                privacy policies governed by "third parties" may be different
                from the one adopted by us, therefore we do not respond to
                third-party sites.
              </p>
              <p>
                <a
                  href="https://www.adroll.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.adroll.com{" "}
                </a>{" "}
                - Digital Marketing, Targeted Advertising
                <br />
                <a
                  href="https://www.bazaarvoice.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.bazaarvoice.com{" "}
                </a>{" "}
                - Digital Marketing and review service, collects data for use in
                interest based advertising
                <br />
                <a
                  href="https://www.google.com/analytics"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.google.com/analytics{" "}
                </a>{" "}
                - Web Analytics, Measures user interaction on our websites
                <br />
                <a
                  href="https://www.qubit.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.qubit.com{" "}
                </a>{" "}
                - Measures how customers use our website, and how the website
                behaves when used by visitors.
                <br />
                <a
                  href="https://www.cloudflare.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.cloudflare.com{" "}
                </a>{" "}
                - Used for web performance and security
                <br />
                <a
                  href="https://www.iban.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.iban.com{" "}
                </a>{" "}
                - Used for bank account validation
                <br />
                <a
                  href="https://www.loqate.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.loqate.com{" "}
                </a>{" "}
                - Used for location intelligence
                <br />
                <a
                  href="https://pricespy.co.uk"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  pricespy.co.uk{" "}
                </a>{" "}
                - Used for Price Comparison - Authentication, tracking of search
                history, last visited products, and many generic settings
                <br />
                <a
                  href="http://www.kelkoo.com"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.kelkoo.com{" "}
                </a>{" "}
                - Used for Price Comparison - estimate audience size and usage
                pattern, store your preferences, speed up your searches,
                statistics
              </p>
              <p>
                <strong>What are your choices regarding Cookies?</strong>
              </p>
              <p>
                When you first log in we offer you the option to personalise
                your cookie set up so you can decide which types of cookies you
                want us to use. It is worth noting that our website along with
                most others wouldn’t work very well without certain cookies.
                They allow us to prevent crashes, display information, fix bugs
                and ensure the security of our site (and your account). These
                types of cookies are often called “Required” cookies. Because
                they are needed for our site to work, we don’t provide you with
                an ability to opt-out of these cookies. But you can remove them
                by using your browser settings. Keep in mind that certain
                features of our site may not be available to you.
              </p>
              <p>
                For more information on how to manage cookies in your browser,
                please visit{" "}
                <a
                  href=" http://www.allaboutcookies.org/manage-cookies"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  www.allaboutcookies.org/manage-cookies{" "}
                </a>
                .
              </p>
              <p>
                You can also learn more about interest based advertising and
                your rights here{" "}
                <a
                  href="https://youradchoices.com/"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                >
                  youradchoices.com{" "}
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CookiesPolicy;
